### ISSUE TITLE
Request help for a conditional capture of a single image

### ISSUE THREAD

**Issue by 18930215187** [NiiightmareXD/windows-capture#1]
I encountered some problems in the call, perhaps the encapsulated function does not match my task, the scenario is as follows: I want a control function condition is true to intercept the desktop, is false to suspend the intercept, do not need to repeat the initialization operation, what should I do to complete this task?

**Comment by 18930215187** [comment]
@NiiightmareXD

**Comment by NiiightmareXD** [comment]
Hi if I understood you want to pause the capture process is that right?

**Comment by NiiightmareXD** [comment]
Ok so it should be pretty simple to do if you want to pause just don't process the frame and return early when at frame arrives and if you want to get the condition to whether pause or not you can use the flags from the settings to give a mutex to the struct new function and then you can start the capture in a new thread and change the mutex when needed.

Let me know if you need help to do that, I can write a simple example.
