### ISSUE TITLE
How to record a program's window instead of full screen 

### ISSUE THREAD

**Issue by QC2168** [NiiightmareXD/windows-capture#115]

**Comment by mycrl** [comment]
Capturing windows in windows has always been a complex problem that can't be handled simply.

The difficulty with capturing windows is that capturing self-rendering windows, such as games or browser pages, requires all sorts of special handling, and it's not a simple thing to do.

As far as I know, the current project is unlikely to support your feature request anytime soon. If you have a need to capture windows, I'd recommend using the core of obs (libobs) to do it, but obs is not a Rust project and the quality of the obs code isn't great, but at the moment using libobs is the best way to work with all types of windows.

**Comment by NiiightmareXD** [comment]
The best thing you could do at the time is to make sure the window size wouldn't change and use the `Window` struct for the capture settings target.
