### ISSUE TITLE
[FEATURE ⭐]

### ISSUE THREAD

**Issue by byteswalk** [NiiightmareXD/windows-capture#28]
I want to add a method to the window object so that it can recognize window handles obtained by external programs, this may not be a good practice, but I need it, if there is a better way to recognize the same HWND between different languages, please provide it

pub fn from_process_id(process_id: u32) -> Result<Self, Error> {
        let windows = Self::enumerate()?;
        let target_window = windows.into_iter().find(|window| {
            let mut window_pid: u32 = 0;
            unsafe {
                GetWindowThreadProcessId(window.window, Some(&mut window_pid));
            }
            window_pid == process_id && unsafe { IsWindowVisible(window.window) }.as_bool()
        });
        target_window.map_or_else(|| Err(Error::NotFound(process_id.to_string())), Ok)
    }

**Comment by NiiightmareXD** [comment]
hmmm, good idea
