### ISSUE TITLE
[BUG 🪲]

### ISSUE THREAD

**Issue by gurubyte** [NiiightmareXD/windows-capture#31]
**Describe the bug 🐛**

main panics when I run program with WithoutBorder setting. If I set Default, it works but it has borders, which I dont want to have.

Got The Flag: Yea This Works
thread 'main' panicked at src\commands\record_video.rs:102:26:
Screen Capture Failed: GraphicsCaptureApiError(BorderConfigUnsupported)

**Expected behavior 📝**
To record a video of a screen that lasts 6 seconds

**OS 🤖**
Windows
Version 10.0.19045 
Build 19045

**Additional context ➕**
```rust
let settings = Settings::new(
    // Item To Captue
    primary_monitor,
    // Capture Cursor Settings
    CursorCaptureSettings::WithCursor,
    // Draw Borders Settings
    DrawBorderSettings::WithoutBorder,
    // The desired color format for the captured frame.
    ColorFormat::Rgba8,
    // Additional flags for the capture settings that will be passed to user defined `new` function.
    "Yea This Works".to_string(),
)
.unwrap();
```

**Comment by NiiightmareXD** [comment]
The API used is quite new and the DrawBorderSettings::WithoutBorder option is not supported in your Windows version you should use DrawBorderSettings::Default;
