### ISSUE TITLE
[BUG 🪲] Doesn't start recording

### ISSUE THREAD

**Issue by gucki** [NiiightmareXD/windows-capture#39]
**Describe the bug 🐛**
I executed the example provided in the README.txt but it doesn't start to record anything. It always stays at recording for 0 seconds:

![image](https://github.com/NiiightmareXD/windows-capture/assets/175494/ccb5e85c-699a-458f-8950-052011297a84)

**Expected behavior 📝**
The example should work and record a few seconds.

**OS 🤖**
 - latest windows 10 running in a qemu vm

**Comment by NiiightmareXD** [comment]
Hey, I'm not sure what's causing the problem, are graphics drivers installed correctly? can you check another screen recording software like OBS to see if that works? also, what is the exact windows version?
