### ISSUE TITLE
[FEATURE ⭐] Improved guide how to setup library

### ISSUE THREAD

**Issue by PmNz8** [NiiightmareXD/windows-capture#43]
**Is your feature request related to a problem? Please describe. 📝**
First - thanks for creating this. Faster and more efficient libraries are always a great thing to have. 

However. I am not experienced with python and the development process / environment. I just created a few simple scripts for myself that I needed but nothing more. I would like to check if one of my script can use this library instead of dxcam but I have troubles setting it up in PyCharm. When I try to perform the 
`pip install windows-capture`
I get the following error:

```
Collecting windows-capture
  Using cached windows_capture-1.0.62.tar.gz (35 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
     
      Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/
     
      Checking for Rust toolchain....
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
I tried to install the Rust plugin inside PyCharm and also installing rustup directly on my machine but none of that helped to solve the issue.

**Describe the solution you'd like 🔑**
A guide, how to properly setup PyCharm (or other environment) to use this library.

**Comment by NiiightmareXD** [comment]
Hey, what is your python version? that may be the problem

**Comment by PmNz8** [comment]
Hi, in PyCharm I have 3.10.6 version.

**Comment by NiiightmareXD** [comment]
I uploaded the version only for 3.11 and 3.12. I'll upload for more versions when I get to it.

**Comment by NiiightmareXD** [comment]
Should be fixed.
