### ISSUE TITLE
How do I pass a buffer from a callback function?

### ISSUE THREAD

**Issue by 18930215187** [NiiightmareXD/windows-capture#44]
**Describe the bug 🐛**
I'm new to rust. I am using tokio's mpsc to pass the structure of the screenshot, but the on_frame_arrived doesn't seem to allow me to pass other parameters into it or capture the required variables from the external environment. How do I design the code structure to do this?

**Expected behavior 📝**
let (tx_img, mut rx_img) = mpsc::channel::&lt; [u8]&gt; (1);
This line of code is under the main function.
I expect frame.buffer() to be passed to tx_img when the on_frame_arrived function is called.

**OS 🤖** Windows11 23H2

**Comment by NiiightmareXD** [comment]
Hey, you should convert the buffer to a vector (Vec<u8>) to be able to pass it into the mpsc channel.

Also I recommend reading this: https://doc.rust-lang.org/book/

**Comment by 18930215187** [comment]
@NiiightmareXD No, my question is how to include the sender of this channel as a parameter in the callback.This sender is coming from the external environment, I don't know how to make this callback function get the sender.

**Comment by NiiightmareXD** [comment]
to use the sender in the `on_frame_arrived` you have to send it using the flags in the settings and set it in the struct then use it from the self parameter from `on_frame_arrived`.
