### ISSUE TITLE
[BUG 🪲] Using `start_free_threaded` does not call `on_closed`

### ISSUE THREAD

**Issue by SegaraRai** [NiiightmareXD/windows-capture#46]
**Describe the bug 🐛**
When starting the capture using `GraphicsCaptureApiHandler::start_free_threaded`, `GraphicsCaptureApiHandler::on_closed`, which should be called when the capture ends, such as when the window disappears, is not called. I have confirmed that it is called correctly when starting the capture using `GraphicsCaptureApiHandler::start`.

**Expected behavior 📝**
`GraphicsCaptureApiHandler::on_closed` is called when the capture is finished.

**OS 🤖**
 - Version: 11
 - Build: 23H2

**Additional context ➕**

```rust
use windows_capture::{
    capture::GraphicsCaptureApiHandler,
    frame::Frame,
    graphics_capture_api::InternalCaptureControl,
    settings::{ColorFormat, CursorCaptureSettings, DrawBorderSettings, Settings},
    window::Window,
};

#[derive(Debug, Default)]
/// A dummy struct to implement the `GraphicsCaptureApiHandler`` trait.
struct Capture;

/// A capture handler implementation for the windows-capture crate.
impl GraphicsCaptureApiHandler for Capture {
    type Flags = ();
    type Error = ();

    fn new(_flags: Self::Flags) -> Result<Self, Self::Error> {
        println!("Capture handler created");
        Ok(Self)
    }

    fn on_frame_arrived(
        &mut self,
        _frame: &mut Frame,
        _control: InternalCaptureControl,
    ) -> Result<(), Self::Error> {
        println!("Frame arrived");
        Ok(())
    }

    fn on_closed(&mut self) -> Result<(), Self::Error> {
        println!("Capture handler closed");
        Ok(())
    }
}

fn main() {
    const TARGET_WINDOW_NAME: &str = "Fork";

    let window = Window::from_contains_name(TARGET_WINDOW_NAME).expect("Failed to find window");

    let settings = Settings::new(
        window,
        CursorCaptureSettings::WithoutCursor,
        DrawBorderSettings::WithoutBorder,
        ColorFormat::Rgba8,
        (),
    );

    // This doesn't return when the window is closed
    let control = Capture::start_free_threaded(settings).expect("Failed to start capture");
    control.wait().expect("Failed to wait for capture"); // For demonstration purposes. We didn't use `wait()` in our actual code.

    // This works
    //Capture::start(settings).expect("Failed to start capture");
}
```

**Comment by SegaraRai** [comment]
OK. I compared the differences between start and start_free_threaded visually and was able to make it work properly by applying the following changes. However, I don't fully understand what's happening in the background.
https://github.com/NiiightmareXD/windows-capture/pull/47/commits/d8db9101abeed7b1123af414bd1de4b60b64cd6c

I'll submit a PR #47 for now, but since I don't understand it completely, feel free to fix it on your end instead of merging it.
Additionally, feel free to use the code in the PR as you like.

**Comment by NiiightmareXD** [comment]
Hey, thank you for the PR the problem was that the GraphicsCaptureItem should be created in the same capturing thread.
