### ISSUE TITLE
[BUG 🪲] ColorFormat::Rgba16F with FrameBuffer::as_raw_nopadding_buffer returns 4 u8 values per pixel

### ISSUE THREAD

**Issue by j2ghz** [NiiightmareXD/windows-capture#49]
**Describe the bug 🐛**
When setting the ColorFormat to Rgba16F, the FrameBuffer::as_raw_nopadding_buffer() will return an array 4 times the amount of pixels on the screen.

**Expected behavior 📝**
The pixel values are supposed to be 2 bytes per color, so 8 bytes per pixel. I would expect that the returned buffer would have a size of WIDTH * HEIGHT * 8 when using ColorFormat::Rgba16F.

**OS 🤖**
 - Version: 11
 - Build: 23H2

**Additional context ➕**
Workaround: It seems that using FrameBuffer::as_raw_buffer() works fine, I don't know if it's intended to use that one instead. In that case it should be mentioned on in a comment on it or the ColorFormat value.

**Comment by NiiightmareXD** [comment]
It should be fixed in v1.2.0.
