### ISSUE TITLE
[FEATURE ⭐]

### ISSUE THREAD

**Issue by molegod** [NiiightmareXD/windows-capture#57]
Hi, could I ask if there's any way to use this library to let's say, capture 1 frame every second until I exit the python script? 

Running the example in the readme captures two frames and then seems to crash?

I'm not too sure how the library works as there doesn't seem to be "grab_frame()" method or etc.

**Comment by molegod** [comment]
*figured it out, my computer was terminating the process early lol

**Comment by molegod** [comment]
actually, is there any update on a grab_frame() method?

**Comment by NiiightmareXD** [comment]
Hey `grab_frame` is not yet available but it's possible to make it without internal changes.
