### ISSUE TITLE
[FEATURE ⭐] ECAL support

### ISSUE THREAD

**Issue by rlewkowicz** [NiiightmareXD/windows-capture#6]
ECAL is an ipc framework that's cross platform. At some point, ill at least make a python integration. I use it for my c++ work.
https://github.com/eclipse-ecal/ecal
https://github.com/kopernikusauto/ecal-rs

I don't know if I have the energy for another tool chain ad language right now to add it to rust. By adding this though, you could support any language ecal supports and have network ability.

**Comment by rlewkowicz** [comment]
I'll take a shot at rust. It seems nice. I'll leave this open in case you're interested.

**Comment by NiiightmareXD** [comment]
Hey, thanks for opening an issue.

I have never worked with ECAL before and I don't think inter-process communication is good for performance because I at least need to copy each frame.

There is already the Python & Rust library and I plan to make one for C/C++ too.

**Comment by rlewkowicz** [comment]
@NiiightmareXD 

120+ frames a second at 1600x2560 using protobuf. Captn proto or something might be faster. You're not really supposed to use protobuf for images but it works very well for me and will serve my needs. 

https://github.com/rlewkowicz/rust-screen-to-ecal/blob/master/src/main.rs

some junk python code to consume:

```
import sys
import time
import numpy
import numpy as np
import cv2
import os
import frame_pb2


import ecal.core.core as ecal_core
from ecal.core.subscriber import ProtoSubscriber


ecal_core.initialize(sys.argv, "frame")

sub = ProtoSubscriber("/frame", frame_pb2.Frame)

while True:
    topic, frame, time = sub.receive()
    if frame.height == 0:
        continue
    
    buf=np.frombuffer(frame.pixel_data, dtype = np.uint8)
    buf=buf.reshape((frame.height, frame.width, 4))
    print(buf.shape)
    cv2.imwrite('./image.png', buf)
    os._exit(0)
    # # image = cv2.imdecode(buf, -1)
    # cv2.imshow('Image', buf)
    # cv2.waitKey(0)
    # cv2.destroyAllWindows()
```

You could always do a bi directional subscribe. Locally it's micro seconds, especially if you use mem backing vs network. 

So the frames wouldn't publish until you request it vs constantly publishing. You'd get it within micro seconds of request. 

For my uses, I'll be creating a dataloader for yolov5. I just want something agnostic I can feed raw data onto. 

We can close this, I just wanted ya to see it incase you find it interesting. 

I really appreciate your work.
