### ISSUE TITLE
[FEATURE ⭐] set FPS of video recording

### ISSUE THREAD

**Issue by MilkClouds** [NiiightmareXD/windows-capture#62]
When I run it, it saves a 30FPS video, but after poring over the source code, I can't figure out where to change it to change the FPS. If there is a simple way to do this, can you help, or if not, can I ask for a feature implementation?

**Comment by MilkClouds** [comment]
I guess adding this to VideoEncoder::new change FPS well, but I'm not sure if it is a proper way.
```
        media_encoding_profile
            .Video()?
            .FrameRate()?
            .SetNumerator(60)?;
        media_encoding_profile
            .Video()?
            .FrameRate()?
            .SetDenominator(1)?;
```

**Comment by MilkClouds** [comment]
But the error occur when I set Numerator bigger than 60; error occur in 90, 120, 144, ...

this error resolved when I use `VideoEncoderType::Hevc` or `VideoEncoderType::Av1` (I manually implemented Av1 part), but it occur when I use `VideoEncoderType::Mp4`. 

I have no clue about why this happen...

**Comment by NiiightmareXD** [comment]
> I have no clue about why this happen...

Seems like it's a Windows API limitation 🤔

**Comment by NiiightmareXD** [comment]
> > I have no clue about why this happen...
> 
> Seems like it's a Windows API limitation 🤔

I rechecked it, and it was true.
