### ISSUE TITLE
[BUG 🪲]  Exception: Capture Session Threw An Exception -> Failed to initialize WinRT

### ISSUE THREAD

**Issue by skibidi-sigma12351** [NiiightmareXD/windows-capture#67]
**Describe the bug 🐛**
getting: Exception: Capture Session Threw An Exception -> Failed to initialize WinRT
in capture.start()

**Expected behavior 📝**
start capturing the screen

**OS 🤖**
 - Version: 22H2
 - Build: 19045.4651

**Additional context ➕**
i saw another guy having this problem and he said restarting fixed but wasnt same on my side

**Comment by NiiightmareXD** [comment]
Hey, it's Windows 10, right?

can you check if the basic example in the repository works?

**Comment by skibidi-sigma12351** [comment]
> Hey, it's Windows 10, right?
> 
> can you check if the basic example in the repository works?

yeah window 10,  when using the basic example it works and saves me a picture of my screen but anytime else im trying to use it without different way it doesnt work and says that error

**Comment by NiiightmareXD** [comment]
> > Hey, it's Windows 10, right?
> > can you check if the basic example in the repository works?
> 
> yeah window 10, when using the basic example it works and saves me a picture of my screen but anytime else im trying to use it without different way it doesnt work and says that error

Where are you trying to capture the screen?
Is it in Tauri or anything that could have possibly initialized WinRT itself?
In that case you could try to start the capture in a new thread and that would work.
