### ISSUE TITLE
[BUG 🪲] DrawBorderSettings::WithBorder or DrawBorderSettings::WithoutBorder causes panic: GraphicsCaptureApiError(BorderConfigUnsupported)

### ISSUE THREAD

**Issue by Kyu** [NiiightmareXD/windows-capture#69]
**Describe the bug 🐛**
Using the settings `DrawBorderSettings::WithBorder` or `DrawBorderSettings::WithoutBorder` causes a `GraphicsCaptureApiError(BorderConfigUnsupported)` panic in 1.2.0 (also when using the git repo as a dependency, as 1.2.1 cannot be found according to cargo)

**Expected behavior 📝**
Regular capture behavior that is seen when using DrawBorderSettings::Default

**OS 🤖**
 - Version: [e.g. 11] Windows 10 Pro
 - Build[e.g. 22H2] 22H2 (19045.4529)

**Additional context ➕**

```rs
let settings = Settings::new(
        primary_monitor,
        CursorCaptureSettings::Default,
        DrawBorderSettings::WithBorder,  // ERROR CAUSED HERE -- Only accepts ::Default
        ColorFormat::Rgba8,
        "Yea This Works".to_string(),
    );
```

<details>
<summary>Full Output</summary>
C:/Users/User/.cargo/bin/cargo.exe run --color=always --package win-cap-tst --bin win-cap-tst</br>
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.12s</br>
     Running `target\debug\win-cap-tst.exe`</br>
Got The Flag: Yea This Works</br>
thread 'main' panicked at src/main.rs:109:44:</br>
Screen Capture Failed: GraphicsCaptureApiError(BorderConfigUnsupported)</br>
stack backtrace:</br>
   0: std::panicking::begin_panic_handler</br>
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library\std\src\panicking.rs:652</br>
   1: core::panicking::panic_fmt</br>
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library\core\src\panicking.rs:72</br>
   2: core::result::unwrap_failed</br>
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library\core\src\result.rs:1679</br>
   3: </br>enum2$&lt;core::result::Result&lt;windows_capture::capture::CaptureControl&lt;win_cap_tst::Capture,alloc::boxed::Box&lt;dyn$&lt;core::error::Error,core::marker::Send,core::marker::Sync&gt;,alloc::alloc::Global&gt; &gt;,enum2$&lt;windows_capture::capture::GraphicsCaptureApiError&lt;allo
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9\library\core\src\result.rs:1059</br>
   4: win_cap_tst::main</br>
             at .\src\main.rs:109</br>
   5: core::ops::function::FnOnce::call_once&lt;void (*)(),tuple$&lt;&gt; &gt;</br>
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9\library\core\src\ops\function.rs:250</br>
   6: core::hint::black_box</br>
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9\library\core\src\hint.rs:338</br>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.</br>
error: process didn't exit successfully: `target\debug\win-cap-tst.exe` (exit code: 101)</br>

Process finished with exit code 101</br>
</details>

**Comment by NiiightmareXD** [comment]
Hey, the panic is in `Capture::start` and it's not a panic you can handle the error currently other options are only supported in windows 11.

**Comment by Kyu** [comment]
@NiiightmareXD you misunderstand me, I meant that the line/value I highlighted is what causes Capture::start to panic, not that the setting construction panics. 

But yea, it would be nice to have wincap gracefully handle the issue when windows is not 11, or at the very least, have this issue documented. For now I'll handle it on my end

**Comment by NiiightmareXD** [comment]
> @NiiightmareXD you misunderstand me, I meant that the line/value I highlighted is what causes Capture::start to panic, not that the setting construction panics.
> 
> But yea, it would be nice to have wincap gracefully handle the issue when windows is not 11, or at the very least, have this issue documented. For now I'll handle it on my end

It doesn't panic, just return an Err(_).

I can't really gracefully handle it without returning to the default behavior which may not be the same as specified in the settings.

**Comment by Kyu** [comment]
@NiiightmareXD yeah understandable, was just looking at the implementation in graphics_capture_api.rs
