### ISSUE TITLE
[FEATURE ⭐] Get pixels of frame

### ISSUE THREAD

**Issue by Niashi24** [NiiightmareXD/windows-capture#71]
**Is your feature request related to a problem? Please describe. 📝**
I would like to use this crate in a SlintUI app to display and capture another window. However, as far as I can tell the only API on the frame is to save it to a file which is of course not an option for something that is real-time, or view the raw buffer the frame uses which changes with the color format, which is not public.

**Describe the solution you'd like 🔑**

Quick solution:
Expose the color format property (read-only), and let the user figure out encodings.

More permanent solution:
Have some API for turning this frame into it's pixels. This can be library specific or use a community crate such as the `image` crate (preferred).

**Comment by NiiightmareXD** [comment]
> **Is your feature request related to a problem? Please describe. 📝** I would like to use this crate in a SlintUI app to display and capture another window. However, as far as I can tell the only API on the frame is to save it to a file which is of course not an option for something that is real-time, or view the raw buffer the frame uses which changes with the color format, which is not public.
> 
> **Describe the solution you'd like 🔑**
> 
> Quick solution: Expose the color format property (read-only), and let the user figure out encodings.
> 
> More permanent solution: Have some API for turning this frame into it's pixels. This can be library specific or use a community crate such as the `image` crate (preferred).

`image` crate is way to slow but I could technically do it manually with a bit of unsafe code.

I will also expose the `ColorFormat`.

**Comment by NiiightmareXD** [comment]
I added a method to get `ColorFormat` you could use `std::slice::from_raw_parts` for convenient.
