### ISSUE TITLE
[FEATURE ⭐] Can you provide a test benchmark code?

### ISSUE THREAD

**Issue by renzhenxuexi0** [NiiightmareXD/windows-capture#72]
```Python
from datetime import datetime
from windows_capture import WindowsCapture, Frame, InternalCaptureControl
import cv2

width, height = 320, 320
left, top = (1920 - width) // 2, (1080 - height) // 2
right, bottom = left + width, top + height
region = (left, top, right, bottom)

capture = WindowsCapture(
    cursor_capture=False,
    draw_border=False,
    monitor_index=None,
    window_name=None,
)

# 开始计时
start_time = datetime.now()
fps_info = f"FPS: 100"
frame_count = 0
global_capture_control = None


# 每次有新帧可用时调用
@capture.event
def on_frame_arrived(frame: Frame, capture_control: InternalCaptureControl):
    global frame_count
    global fps_info
    global start_time, global_capture_control
    global_capture_control = capture_control
    # 使用dxcam捕获屏幕
    img = cv2.cvtColor(frame.crop(left, top, right, bottom).frame_buffer, cv2.COLOR_BGR2BGRA)
    # 计算FPS
    frame_count += 1
    if frame_count >= 100:
        fps_info = f"FPS: {frame_count / (datetime.now() - start_time).total_seconds():.2f}"
        frame_count = 0
        start_time = datetime.now()

        # 在图像上添加FPS信息
        cv2.putText(img, fps_info, (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2)

        # 显示图像
        cv2.imshow("Screen", img)
    # 按q键退出循环
    if cv2.waitKey(1) & 0xFF == ord('q') and global_capture_control is not None:
        global_capture_control.stop()


# Called When The Capture Item Closes Usually When The Window Closes, Capture
# Session Will End After This Function Ends
@capture.event
def on_closed():
    print("Capture Session Closed")
    # 清理资源
    cv2.destroyAllWindows()


capture.start()
```
![image](https://github.com/user-attachments/assets/08e2f865-f3da-4ea0-963b-3b4378f25fd0)
The above is the test code and my CPU model.
```Python
from datetime import datetime

import cv2
import numpy as np
# Microsoft Windows
from mss.windows import MSS as mss

# 获取屏幕大小
width, height = 320, 320
left, top = (1920 - width) // 2, (1080 - height) // 2
right, bottom = left + width, top + height
region = (left, top, right, bottom)
sct = mss()
monitor = {
    "left": left,
    "top": top,
    "width": width,
    "height": height,
}

# 开始计时
start_time = datetime.now()
fps_info = f"FPS: 100"
frame_count = 0

try:
    while "Screen capturing":
        # 使用mss捕获屏幕
        img = np.array(sct.grab(monitor))

        # 计算FPS
        frame_count += 1
        if frame_count >= 100:
            fps_info = f"FPS: {frame_count / (datetime.now() - start_time).total_seconds():.2f}"
            frame_count = 0
            start_time = datetime.now()
        # 在图像上添加FPS信息
        cv2.putText(img, fps_info, (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2)

        # 显示图像
        cv2.imshow("Screen", img)

        # 按q键退出循环
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

finally:
    # 清理资源
    sct.close()
    cv2.destroyAllWindows()
```
This is the test code of MSS.
![image](https://github.com/user-attachments/assets/12451b7e-3018-4b2e-90f8-e89d5a2c4e2b)
![image](https://github.com/user-attachments/assets/88ca1e64-dd00-4117-9c94-57e2a2139144)
The picture above is the result of the test.
Is there any problem with my code, please give me a point.

**Comment by renzhenxuexi0** [comment]
Added that the slowest is Windows_capture.

**Comment by NiiightmareXD** [comment]
Hey, I think this is something to do with cv2 here is my benchmark which windows-capture is a lot faster.

mss:
```py
import time
from mss.windows import MSS as mss

def calculate_fps():
    sct = mss()
    frame_count = 0
    last_time = time.time()

    try:
        while True:
            sct.shot()
            frame_count += 1
            current_time = time.time()
            
            if current_time - last_time >= 1:
                fps = frame_count / (current_time - last_time)
                print(f"FPS: {fps:.2f}")
                frame_count = 0
                last_time = current_time

    except KeyboardInterrupt:
        print("Screen capturing stopped.")

if __name__ == "__main__":
    calculate_fps()
```

windows-capture:
```py
from windows_capture import WindowsCapture, Frame, InternalCaptureControl
import time

frame_count = 0
last_time = time.time()

capture = WindowsCapture(
    cursor_capture=None,
    draw_border=None,
    monitor_index=None,
    window_name=None,
)

@capture.event
def on_frame_arrived(frame: Frame, _capture_control: InternalCaptureControl):
    global frame_count
    global last_time
    
    _frame_buffer = frame.frame_buffer

    frame_count += 1
    current_time = time.time()
    
    if current_time - last_time >= 1:
        fps = frame_count / (current_time - last_time)
        print(f"FPS: {fps:.2f}")
        frame_count = 0
        last_time = current_time

@capture.event
def on_closed():
    print("Capture Session Closed")


capture.start()
```

**Comment by NiiightmareXD** [comment]
One thing to note is that windows-capture only calls the callback function when there is something new on the screen so as to benchmark its full potential and other libraries I made a DirectX game to refresh as fast as possible.

**Comment by NiiightmareXD** [comment]
I couldn't replicate your OpenCV example problem, both of them achieve a constant 60 fps.

can you share your hardware info?

**Comment by renzhenxuexi0** [comment]
Oh, thanks for the reply. My work computer only has cpu core, I think I know what you are talking about, it does cause slowdowns, probably because my computer doesn't have a discrete graphics card.

**Comment by NiiightmareXD** [comment]
Also try jiggling your mouse cursor when capturing with opencv to force a update if you want to benchmark the FPS.

**Comment by renzhenxuexi0** [comment]
Thank you, I will try it

**Comment by cryonox** [comment]
@renzhenxuexi0 hi I believe this is because you cannot do any work in `on_frame_event`. The conversion of BGRA hurts performance a lot. The unfortunate thing is it even slows down the original application fps by a sizeable amount. It would also be good if @NiiightmareXD can provide a sample that not only just ignore the frame but do some actual work(even something as trivial as displaying the frame). 

IMO,with the way the graphics capture api work, it might be necessary to provide more infrastructure for actual usage such as very fast copying of frame buffer in `on_frame_event` (i.e don't do any work in on_frame_event, but copy it to a buffer and let another thread do the display).

**Comment by NiiightmareXD** [comment]
> @renzhenxuexi0 hi I believe this is because you cannot do any work in `on_frame_event`. The conversion of BGRA hurts performance a lot. The unfortunate thing is it even slows down the original application fps by a sizeable amount. It would also be good if @NiiightmareXD can provide a sample that not only just ignore the frame but do some actual work(even something as trivial as displaying the frame). Naturally, the users of the library use the library for something useful such as doing further processing on the captured frames. So I think the benchmark methodology should reflect this reality.
> 
> IMO,with the way the graphics capture api work, it might be necessary to provide more infrastructure for actual usage such as very fast copying of frame buffer in `on_frame_event` (i.e don't do any work in on_frame_event, but copy it to a buffer and let another thread do the display).

I'll provide a few benchmark tests, about the to_bgr method you don't need to actually call it most of the time the default format is BGRA and in your first OpenCV code you convert it to BGRA again which could be avoided.

**Comment by cryonox** [comment]
@renzhenxuexi0 try this.
```
from windows_capture import WindowsCapture, Frame, InternalCaptureControl
import cv2
import numpy as np
import time
import threading
capture = WindowsCapture(
    cursor_capture=None,
    draw_border=False,
    monitor_index=None,
    window_name=None,
)


frame_copy = None
@capture.event
def on_frame_arrived(frame: Frame, capture_control: InternalCaptureControl):
    global frame_copy
    frame_copy = frame


@capture.event
def on_closed():
    print("Capture Session Closed")

should_continue= True
def display():
    global frame_copy,stop
    while should_continue:
        if frame_copy is not None:
            img = cv2.cvtColor(frame_copy.frame_buffer, cv2.COLOR_BGR2BGRA)
            cv2.imshow('im',img)
            cv2.waitKey(1)
        else:
            time.sleep(1)

t = threading.Thread(target=display)
t.start()
try:
    capture.start()
except:
    should_continue=False
    t.join() 
t.join()
```

**Comment by cryonox** [comment]
@NiiightmareXD it would also be nice if you can add this piece of code to your library. This removes the top window title bar and behaves like OBS hide `client_area` mode.

```python
from windows_capture import WindowsCapture, Frame, InternalCaptureControl
import cv2
import numpy as np
import time
import threading

import win32gui
import win32ui
import win32api
import win32con
import ctypes

def set_dpi_awareness():
    awareness = ctypes.c_int()
    errorCode = ctypes.windll.shcore.GetProcessDpiAwareness(
        0, ctypes.byref(awareness))
    errorCode = ctypes.windll.shcore.SetProcessDpiAwareness(2)
    success = ctypes.windll.user32.SetProcessDPIAware()

def get_title_bar_dimensions(win_title):
    set_dpi_awareness()
    hwnd = win32gui.FindWindow(None, win_title)
    x1, y1, x2, y2 = win32gui.GetClientRect(hwnd)
    width = x2-x1
    height = y2-y1
    wx1, wy1, wx2, wy2 = win32gui.GetWindowRect(hwnd)
    wx1, wx2 = wx1-wx1, wx2-wx1
    wy1, wy2 = wy1-wy1, wy2-wy1
    bw = int((wx2-x2)/2.)
    th = wy2-y2-bw
    return th,bw

window_name = 'Untitled - Paint'
capture = WindowsCapture(
    cursor_capture=None,
    draw_border=False,
    monitor_index=None,
    window_name=window_name
)


frame_copy = None
@capture.event
def on_frame_arrived(frame: Frame, capture_control: InternalCaptureControl):
    global frame_copy
    frame_copy = frame


@capture.event
def on_closed():
    print("Capture Session Closed")


should_continue= True
def display():
    global frame_copy,stop
    while should_continue:
        if frame_copy is not None:
            th,bw = get_title_bar_dimensions(window_name)
            cv2.imshow('im',frame_copy.frame_buffer[th-bw:,:,:])
            cv2.waitKey(1)
        else:
            time.sleep(1)

t = threading.Thread(target=display)
t.start()
try:
    capture.start()
except:
    should_continue=False
    t.join() 
t.join()


```

**Comment by NiiightmareXD** [comment]
should I add `client_area` as an option?

**Comment by NiiightmareXD** [comment]
by the way, could you try the Rust version of `windows-capture` to record the game?
I've been capturing Valorant with it for a year now with little to no performance hit.

The problem might be from my Python implementation because I didn't consider OpenCV's compatibility.

**Comment by cryonox** [comment]
> should I add `client_area` as an option?

Ya maybe something like `only_client_area` boolean value? Then if it's true, it should not include the top title. 

![image](https://github.com/user-attachments/assets/feaf24dd-e1f2-467c-a9f5-893428a93cfc)


> by the way, could you try the Rust version of `windows-capture` to record the game? I've been capturing Valorant with it for a year now with little to no performance hit.
> 
> The problem might be from my Python implementation because I didn't consider OpenCV's compatibility.

ok I will take a look. The problem is most definitely with python.
