### ISSUE TITLE
[FEATURE ⭐] Performance issues with textures inside frames

### ISSUE THREAD

**Issue by mycrl** [NiiightmareXD/windows-capture#75]
Now, operating textures inside Frame, such as Map array or copying resources, all create a new texture, but according to my discovery, textures seem to be reusable.
This comes from other people's implementations or codes I have seen in the past two days, and I forgot which official tutorial I saw this usage from, because window capture is quite linear, the next frame always covers the previous frame, and for the current library design, it is impossible to continue to hold the reference of the previous frame when the next frame comes. Can this texture be made into only one copy in the capture thread, and only references are distributed in Frame, and CopyResource can overwrite this texture at any time, which does not seem to conflict.
The performance improvement does not seem to be very large, but it is probably an optimizable point.
I am not a D3D expert, please forgive me if there are any errors.

**Comment by mycrl** [comment]
This question probably needs to be put aside for now. I am working on using swap chains to scale textures. I will open a merge request later, but I will probably only do some preliminary work to make the feature work by supporting in-gpu scaling. This update will be relatively large, so the texture part will change;

I have done some work, but there are still some obstacles waiting to be fixed. However, I think this feature is still needed. Software scaling on the CPU is very slow. Offloading this task to the GPU will improve performance a lot. If it is downsampled, it can also reduce the size of the data copied from the GPU, because only the downscaled data needs to be processed, which should improve some memory IO

**Comment by NiiightmareXD** [comment]
This can be easily done when capturing the whole monitor, because the size doesn't change.
The current implementation is a copy of what OBS does with a little bit of change.
It would be nice if we could improve it.

**Comment by mycrl** [comment]
Indeed, I overlooked this problem. If only a certain area is captured after capture, how to do the scaling logic is still a problem. Therefore, scaling cannot be included in the current capture process. If it must be added, it can only be done through expansion, similar to the video encoder in this project, which can only be added to post-processing after the capture process.

**Comment by mycrl** [comment]
Let’s close it first. There are a lot of things to consider right now, so it’s not a good time to start this feature.

**Comment by NiiightmareXD** [comment]
Ok, makes sense.
