### ISSUE TITLE
[BUG 🪲] example is inconsistent with the actual situation

### ISSUE THREAD

**Issue by thelostword** [NiiightmareXD/windows-capture#76]
**Describe the bug 🐛**
![image](https://github.com/user-attachments/assets/619874ce-9ba2-4746-bfce-6db21cfce21b)
`AudioSettingsBuilder` actually should be `AudioSettingBuilder ` 

**Expected behavior 📝**

**OS 🤖**
 - Version: [e.g. 11]
 - Build[e.g. 22H2]

**Additional context ➕**

**Comment by thelostword** [comment]
should we modify the example code by changing `AudioSettingsBuilder` to `AudioSettingBuilder` or by modifying the code of src. this will be inconsistent with the naming of `VideoSettingsBuilder`

**Comment by NiiightmareXD** [comment]
True, I'll fix it, thanks for pointing it out.

**Comment by thelostword** [comment]
> Hey, where is this error? I can't seem to find it

Sorry, it should be a version issue. The latest version on crates is 1.3.2, while the repository version is 1.3.5. This issue has already been fixed in [#6853d4f1e29460659b59724dcc1afc661a40a803](https://github.com/NiiightmareXD/windows-capture/commit/6853d4f1e29460659b59724dcc1afc661a40a803).
