### ISSUE TITLE
[BUG 🪲] I get 42 errors when running the example

### ISSUE THREAD

**Issue by JohnAllen** [NiiightmareXD/windows-capture#77]
**Describe the bug 🐛**
I get 42 compile errors when I run the example. 

I cloned the repo and ran the example and still got them

**Expected behavior 📝**
For the example to work when running it

**OS 🤖**
 - Version: Mac OS 14.3.1 (23D60)
 - Build[e.g. 22H2]

**Additional context ➕**
Here is the compiler output:

~/windows-capture cargo run --example basic 
   Compiling windows-targets v0.52.6
   Compiling scopeguard v1.2.0
   Compiling cfg-if v1.0.0
   Compiling smallvec v1.13.2
   Compiling either v1.13.0
   Compiling crossbeam-utils v0.8.20
   Compiling libc v0.2.155
   Compiling syn v2.0.72
   Compiling windows-result v0.2.0
   Compiling lock_api v0.4.12
   Compiling windows-strings v0.1.0
   Compiling parking_lot_core v0.9.10
   Compiling crossbeam-epoch v0.9.18
   Compiling parking_lot v0.12.3
   Compiling crossbeam-deque v0.8.5
   Compiling rayon-core v1.12.1
   Compiling rayon v1.10.0
   Compiling windows-implement v0.58.0
   Compiling windows-interface v0.58.0
   Compiling thiserror-impl v1.0.63
   Compiling windows-core v0.58.0
   Compiling thiserror v1.0.63
   Compiling windows v0.58.0
   Compiling windows-capture v1.3.5 (/Users/john/windows-capture)
error[E0433]: failed to resolve: could not find `windows` in `os`
   --> src/capture.rs:3:9
    |
3   |     os::windows::prelude::AsRawHandle,
    |         ^^^^^^^ could not find `windows` in `os`
    |
note: found an item that was configured out
   --> /Users/john/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/os/mod.rs:53:9
    |
53  | pub mod windows {}
    |         ^^^^^^^
note: found an item that was configured out
   --> /Users/john/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/os/mod.rs:100:9
    |
100 | pub mod windows;
    |         ^^^^^^^

error[E0433]: failed to resolve: could not find `Graphics` in `windows`
  --> src/capture.rs:14:5
   |
14 |     Graphics::Capture::GraphicsCaptureItem,
   |     ^^^^^^^^ could not find `Graphics` in `windows`

error[E0433]: failed to resolve: could not find `Win32` in `windows`
  --> src/capture.rs:15:5
   |
15 |     Win32::{
   |     ^^^^^ could not find `Win32` in `windows`

error[E0432]: unresolved import `windows::Foundation`
  --> src/capture.rs:13:5
   |
13 |     Foundation::AsyncActionCompletedHandler,
   |     ^^^^^^^^^^ could not find `Foundation` in `windows`

error[E0433]: failed to resolve: could not find `Graphics` in `windows`
 --> src/d3d11.rs:3:5
  |
3 |     Graphics::DirectX::Direct3D11::IDirect3DDevice,
  |     ^^^^^^^^ could not find `Graphics` in `windows`

error[E0433]: failed to resolve: could not find `Win32` in `windows`
 --> src/d3d11.rs:4:5
  |
4 |     Win32::{
  |     ^^^^^ could not find `Win32` in `windows`

error[E0432]: unresolved import `windows::core`
 --> src/d3d11.rs:2:5
  |
2 |     core::Interface,
  |     ^^^^ could not find `core` in `windows`

error[E0433]: failed to resolve: could not find `Graphics` in `windows`
  --> src/encoder.rs:16:5
   |
16 |     Graphics::{
   |     ^^^^^^^^ could not find `Graphics` in `windows`

error[E0433]: failed to resolve: could not find `Media` in `windows`
  --> src/encoder.rs:20:5
   |
20 |     Media::{
   |     ^^^^^ could not find `Media` in `windows`

error[E0433]: failed to resolve: could not find `Security` in `windows`
  --> src/encoder.rs:32:5
   |
32 |     Security::Cryptography::CryptographicBuffer,
   |     ^^^^^^^^ could not find `Security` in `windows`

error[E0433]: failed to resolve: could not find `Storage` in `windows`
  --> src/encoder.rs:33:5
   |
33 |     Storage::{
   |     ^^^^^^^ could not find `Storage` in `windows`

error[E0432]: unresolved imports `windows::core`, `windows::Foundation`, `windows::Storage`
  --> src/encoder.rs:14:5
   |
14 |     core::HSTRING,
   |     ^^^^ could not find `core` in `windows`
15 |     Foundation::{EventRegistrationToken, TimeSpan, TypedEventHandler},
   |     ^^^^^^^^^^ could not find `Foundation` in `windows`
...
33 |     Storage::{
   |     ^^^^^^^ could not find `Storage` in `windows`

error[E0433]: failed to resolve: could not find `Graphics` in `windows`
  --> src/frame.rs:11:5
   |
11 |     Graphics::DirectX::Direct3D11::IDirect3DSurface,
   |     ^^^^^^^^ could not find `Graphics` in `windows`

error[E0433]: failed to resolve: could not find `Win32` in `windows`
  --> src/frame.rs:12:5
   |
12 |     Win32::Graphics::{
   |     ^^^^^ could not find `Win32` in `windows`

error[E0432]: unresolved import `windows::Foundation`
  --> src/frame.rs:10:5
   |
10 |     Foundation::TimeSpan,
   |     ^^^^^^^^^^ could not find `Foundation` in `windows`

error[E0433]: failed to resolve: could not find `Foundation` in `windows`
 --> src/graphics_capture_api.rs:9:5
  |
9 |     Foundation::{EventRegistrationToken, Metadata::ApiInformation, TypedEventHandler},
  |     ^^^^^^^^^^ could not find `Foundation` in `windows`

error[E0433]: failed to resolve: could not find `Graphics` in `windows`
  --> src/graphics_capture_api.rs:10:5
   |
10 |     Graphics::{
   |     ^^^^^^^^ could not find `Graphics` in `windows`

error[E0433]: failed to resolve: could not find `Win32` in `windows`
  --> src/graphics_capture_api.rs:14:5
   |
14 |     Win32::{
   |     ^^^^^ could not find `Win32` in `windows`

error[E0432]: unresolved imports `windows::core`, `windows::Foundation`
 --> src/graphics_capture_api.rs:8:5
  |
8 |     core::{IInspectable, Interface, HSTRING},
  |     ^^^^ could not find `core` in `windows`
9 |     Foundation::{EventRegistrationToken, Metadata::ApiInformation, TypedEventHandler},
  |     ^^^^^^^^^^ could not find `Foundation` in `windows`

error[E0433]: failed to resolve: could not find `Graphics` in `windows`
 --> src/monitor.rs:5:5
  |
5 |     Graphics::Capture::GraphicsCaptureItem,
  |     ^^^^^^^^ could not find `Graphics` in `windows`

error[E0433]: failed to resolve: could not find `Win32` in `windows`
 --> src/monitor.rs:6:5
  |
6 |     Win32::{
  |     ^^^^^ could not find `Win32` in `windows`

error[E0433]: failed to resolve: could not find `Graphics` in `windows`
 --> src/settings.rs:1:14
  |
1 | use windows::Graphics::Capture::GraphicsCaptureItem;
  |              ^^^^^^^^ could not find `Graphics` in `windows`

error[E0432]: unresolved import `windows::core`
 --> src/monitor.rs:4:5
  |
4 |     core::{HSTRING, PCWSTR},
  |     ^^^^ could not find `core` in `windows`

error[E0433]: failed to resolve: could not find `Graphics` in `windows`
 --> src/window.rs:5:5
  |
5 |     Graphics::Capture::GraphicsCaptureItem,
  |     ^^^^^^^^ could not find `Graphics` in `windows`

error[E0433]: failed to resolve: could not find `Win32` in `windows`
 --> src/window.rs:6:5
  |
6 |     Win32::{
  |     ^^^^^ could not find `Win32` in `windows`

error[E0432]: unresolved import `windows::core`
 --> src/window.rs:4:5
  |
4 |     core::HSTRING,
  |     ^^^^ could not find `core` in `windows`

error[E0433]: failed to resolve: could not find `core` in `windows`
   --> src/capture.rs:304:52
    |
304 |                 move |_, _| -> Result<(), windows::core::Error> {
    |                                                    ^^^^ could not find `core` in `windows`

error[E0433]: failed to resolve: could not find `core` in `windows`
   --> src/capture.rs:425:60
    |
425 |                         move |_, _| -> Result<(), windows::core::Error> {
    |                                                            ^^^^ could not find `core` in `windows`

error[E0433]: failed to resolve: could not find `core` in `windows`
  --> src/d3d11.rs:26:35
   |
26 |     WindowsError(#[from] windows::core::Error),
   |                                   ^^^^ could not find `core` in `windows`

error[E0433]: failed to resolve: could not find `core` in `windows`
  --> src/encoder.rs:52:35
   |
52 |     WindowsError(#[from] windows::core::Error),
   |                                   ^^^^ could not find `core` in `windows`

error[E0433]: failed to resolve: could not find `core` in `windows`
   --> src/encoder.rs:150:35
    |
150 |     WindowsError(#[from] windows::core::Error),
    |                                   ^^^^ could not find `core` in `windows`

error[E0433]: failed to resolve: could not find `core` in `windows`
  --> src/frame.rs:38:35
   |
38 |     WindowsError(#[from] windows::core::Error),
   |                                   ^^^^ could not find `core` in `windows`

error[E0433]: failed to resolve: could not find `core` in `windows`
  --> src/graphics_capture_api.rs:44:35
   |
44 |     WindowsError(#[from] windows::core::Error),
   |                                   ^^^^ could not find `core` in `windows`

error[E0433]: failed to resolve: could not find `core` in `windows`
  --> src/monitor.rs:44:35
   |
44 |     WindowsError(#[from] windows::core::Error),
   |                                   ^^^^ could not find `core` in `windows`

error[E0433]: failed to resolve: could not find `core` in `windows`
   --> src/monitor.rs:477:32
    |
477 |         let interop = windows::core::factory::<Self, IGraphicsCaptureItemInterop>()?;
    |                                ^^^^ could not find `core` in `windows`

error[E0433]: failed to resolve: could not find `core` in `windows`
  --> src/window.rs:31:35
   |
31 |     WindowsError(#[from] windows::core::Error),
   |                                   ^^^^ could not find `core` in `windows`

error[E0433]: failed to resolve: could not find `core` in `windows`
   --> src/window.rs:259:32
    |
259 |         let interop = windows::core::factory::<Self, IGraphicsCaptureItemInterop>()?;
    |                                ^^^^ could not find `core` in `windows`

error[E0599]: no method named `as_raw_handle` found for struct `JoinHandle` in the current scope
   --> src/capture.rs:161:40
    |
161 |             let handle = thread_handle.as_raw_handle();
    |                                        ^^^^^^^^^^^^^ method not found in `JoinHandle<Result<(), GraphicsCaptureApiError<E>>>`

error[E0599]: the method `map_err` exists for enum `Result<GraphicsCaptureApi, Error>`, but its trait bounds were not satisfied
   --> src/capture.rs:284:10
    |
275 |           let mut capture = GraphicsCaptureApi::new(
    |  ___________________________-
276 | |             item,
277 | |             callback,
278 | |             settings.cursor_capture,
...   |
283 | |         )
284 | |         .map_err(GraphicsCaptureApiError::GraphicsCaptureApiError)?;
    | |         -^^^^^^^ method cannot be called on `Result<GraphicsCaptureApi, Error>` due to unsatisfied trait bounds
    | |_________|
    |
    |
   ::: src/graphics_capture_api.rs:76:1
    |
76  |   pub struct GraphicsCaptureApi {
    |   ----------------------------- doesn't satisfy `GraphicsCaptureApi: Sized`
    |
    = note: the following trait bounds were not satisfied:
            `{type error}: Sized`
            which is required by `GraphicsCaptureApi: Sized`

error[E0599]: the method `map_err` exists for enum `Result<GraphicsCaptureApi, Error>`, but its trait bounds were not satisfied
   --> src/capture.rs:397:18
    |
388 |                   let mut capture = GraphicsCaptureApi::new(
    |  ___________________________________-
389 | |                     item,
390 | |                     callback.clone(),
391 | |                     settings.cursor_capture,
...   |
396 | |                 )
397 | |                 .map_err(GraphicsCaptureApiError::GraphicsCaptureApiError)?;
    | |                 -^^^^^^^ method cannot be called on `Result<GraphicsCaptureApi, Error>` due to unsatisfied trait bounds
    | |_________________|
    |
    |
   ::: src/graphics_capture_api.rs:76:1
    |
76  |   pub struct GraphicsCaptureApi {
    |   ----------------------------- doesn't satisfy `GraphicsCaptureApi: Sized`
    |
    = note: the following trait bounds were not satisfied:
            `{type error}: Sized`
            which is required by `GraphicsCaptureApi: Sized`

error[E0599]: no method named `get` found for struct `Vec` in the current scope
   --> src/monitor.rs:101:37
    |
101 |         let monitor = match monitor.get(index - 1) {
    |                                     ^^^ method not found in `Vec<Monitor>`

error[E0277]: `Vec<Window>` is not an iterator
   --> src/window.rs:106:23
    |
106 |         for window in windows {
    |                       ^^^^^^^ `Vec<Window>` is not an iterator; try calling `.into_iter()` or `.iter()`
    |
    = help: the trait `IntoIterator` is not implemented for `Vec<Window>`
    = help: the following other types implement trait `IntoIterator`:
              &'a Vec<T, A>
              &'a mut Vec<T, A>
              Vec<T, A>

**Comment by NiiightmareXD** [comment]
Hey this library is windows only.
Checkout: https://github.com/CapSoftware/scap
