### ISSUE TITLE
[BUG 🪲] Unable to save frame as an image

### ISSUE THREAD

**Issue by WallyOxen** [NiiightmareXD/windows-capture#93]
**Describe the bug 🐛**
I'm not sure if your library is to blame or some wonkiness with the Windows crates/ my version of Windows. I was following the example in the README, added windows-capture v1.4.0 to my project and copied the example into my main.rs file. It runs as expected and saves a 6 second clip. If I uncomment the line `frame.save_as_image("frame.png", ImageFormat::Png)?;` and import the required Type. I get an error: Screen Capture Failed: FrameHandlerError(WindowsError(Error { code: HRESULT(0x80070057), message: "The parameter is incorrect." }))

I tried to dig into it a bit, but I'm fairly new to Rust and don't understand Windows APIs much at all. It seems to be coming from the frame.buffer function during the `texture_desc` declaration. I was able to get past the error then if I hard coded the `Format` from `DXGI_FORMAT(self.color_format as u32)` to just be `DXGI_FORMAT(28)` (Rgba8 default). I also was able to change the underlying DXGI_FORMAT struct to handle `i32` instead of `u32` and changed all of the formats to align as well and that also resolved this issue.

However, even after I hardcode that value it makes it to the `self.context.Map` function to "Map the texture to enable CPU access" with the same error as above and seems to be something with the `D3D11_MAPPED_SUBRESOURCE::default()`, but that's where it gets into the Windows API and I'm really not sure of anything there. So this also makes me think it might not be an issue with your crate.

**Expected behavior 📝**
I expect to get an image saved and overwritten with each frame that's captured during the 6 second recording

**OS 🤖**
 - Version: 11
 - Build: 23H2

**Comment by BenedictWilkins** [comment]
Also facing this issue...

**Comment by WallyOxen** [comment]
@BenedictWilkins Out of curiosity what version and build of windows are you using?

**Comment by BenedictWilkins** [comment]
@WallyOxen 
OS Name	Microsoft Windows 11 Home
Version	10.0.22631 Build 22631

did reverting to that commit not work for you?

**Comment by WallyOxen** [comment]
@BenedictWilkins I was just now able to test it out. After messing with the missing `capture::Context` I was indeed able to get it to output screenshots

**Comment by WallyOxen** [comment]
It seems that [this commit](https://github.com/NiiightmareXD/windows-capture/commit/9d3109d4efc4502be6322293bb8d62398d31f3eb) changed frame.rs:205 and removed the `D3D11_CPU_ACCESS_WRITE.0 as u32` flag. If I add that back in things work as well

**Comment by mycrl** [comment]
> It seems that [this commit](https://github.com/NiiightmareXD/windows-capture/commit/9d3109d4efc4502be6322293bb8d62398d31f3eb) changed frame.rs:205 and removed the `D3D11_CPU_ACCESS_WRITE.0 as u32` flag. If I add that back in things work as well

@WallyOxen Ha ha ha, I created this commit, I removed the CPU writable flag and didn't realize it would affect other places.
But what I'm wondering is that adding writable flags to texture doesn't seem to make much sense, right? Realistically there shouldn't be a need to do a write operation to a captured texture.

**Comment by mycrl** [comment]
https://github.com/NiiightmareXD/windows-capture/blob/0f220752f94843e850f0503834298625fc0921f6/src/frame.rs#L337

I think I know why, I didn't realize that I would wrap the texture's buffer in `&mut [u8]`, and in a screen capture scenario it would not normally be written to an already captured texture.
Sorry, I was going to have the writable flag removed because it didn't make sense, but it doesn't look like I can do that.

**Comment by mycrl** [comment]
@NiiightmareXD It looks like you need to do a quick fix to fix this, there is an issue with my merge request.

**Comment by mycrl** [comment]
#94  I created a bug fix waiting to be merged.

**Comment by NiiightmareXD** [comment]
I will publish the new version and the problem should be fixed.

**Comment by NiiightmareXD** [comment]
Thanks for your recent help @mycrl, I will invite you to collaborators.
